---
title: "Preprocessing diet and continuous glucose monitoring data"
author: "Heather HAll"
date: 2015-08-05
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->

</br></br>

# **under construction... come back soon**



```{r setFileNames, message = F, include = F}

personal.library.directory = "../code"
food.data.path =  "/Users/hhall/predictingGlucoseSpikesPrelim/foodLogs.csv"
conversion.chart.path = "/Users/hhall/Box Sync/Heathers Externally Shareable Files/Snyder/Food Logs/graphs/food_chart.txt"
glucose.file = "/Users/hhall/Box\ Sync/Heathers Externally Shareable Files/Snyder/Glucose/001_data/glucose_data_R.txt"
travel.file = "/Users/hhall/Box\ Sync/Heathers Externally Shareable Files/Snyder/Calendar/flight_times_July.txt"
TZ.path = "/Users/hhall/Box Sync/Heathers Externally Shareable Files/Snyder/Calendar/timezone_codes.txt"
food.timing.file = "/Users/hhall/Box Sync/Heathers Externally Shareable Files/Snyder/Calendar/food_timing.txt"


```

# Load libraries
<!-- load libraries -->
```{r loadLibraries, message = F, include=T}

library("lubridate") # work with times
library("leaps") # regsubset
library("kknn") # k nearest neighbor
library("gbm") # boosting
library("randomForest") # random forest
library(gridExtra); library(grid); library(gtable) # plot tables
library("ggplot2") # ggplot

# load personal library
source(paste(personal.library.directory, "project_library.R", sep = "/"))

```

# Read in files
```{r readFiles, message = F}

# read in myfitnesspal data and recorded meal timing
food.logs = readMyFitnessPal(food.data.path, conversion.chart.path)
food.times <- read.delim(food.timing.file, stringsAsFactors = FALSE)

# read in glucose data
cgm.readings = readDexcomFile(glucose.file)

```

# Annotate glucose spikes
```{r markGlucosePeaks}
min.peak = 120
min.peak.height = 30
cgm.readings = markGlucosePeaks(cgm.readings, min.peak.height, min.peak)


# count number of peaks
table(cgm.readings[which(cgm.readings$peak %in% c("max","min")),]$peak)
```

# Data exclusion
```{r dataExclusion}

# keep only dates with recorded meal times
dates.with.meal.times <- unique(food.times$Date)
cgm.readings <- cgm.readings[which(cgm.readings$GlucoseDisplayDate %in% dates.with.meal.times),] 

# count number of peaks
table(cgm.readings[which(cgm.readings$peak %in% c("max","min")),]$peak)


# remove travel from glucose data and food timing
cgm.readings = removeTravelDates(cgm.readings, travel.file, TZ.path)
food.times = food.times[food.times$Date %in% cgm.readings$GlucoseDisplayDate, ] 


# print number of days removed from travel

# examine number of peaks
table(cgm.readings[which(cgm.readings$peak %in% c("max","min")),]$peak)

```

</br></br> 

## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
