---
title: "Feature selection"
author: "Heather Hall"
date: 2015-08-05
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->

```{r preprocessingCode, message = F, include = F}


########################################################
#   Libraries
########################################################


library("lubridate")

# # library for classification
library("leaps") # regsubset
library("kknn")
library("gbm")
library("randomForest")

# visualization
library(gridExtra); library(grid); library(gtable)
library("ggplot2")

personal.library.directory = "/Users/hhall/predictingGlucoseSpikesPrelim/code"
source(paste(personal.library.directory, "project_library.R", sep = "/"))

########################################################
### Read in Files
########################################################


# file paths
# ------------
food.data.path =  "/Users/hhall/predictingGlucoseSpikesPrelim_data/foodLogs.csv"
conversion.chart.path = "/Users/hhall/predictingGlucoseSpikesPrelim_data/food_chart.txt"
glucose.file = "/Users/hhall/predictingGlucoseSpikesPrelim_data/glucose_data_R.txt"
travel.file = "/Users/hhall/predictingGlucoseSpikesPrelim_data/flight_times_July.txt"
TZ.path = "/Users/hhall/predictingGlucoseSpikesPrelim_data/timezone_codes.txt"
food.timing.file = "/Users/hhall/predictingGlucoseSpikesPrelim_data/food_timing.txt"



# read in myfitnesspal data and recorded meal timing
food.logs = readMyFitnessPal(food.data.path, conversion.chart.path)
food.times <- read.delim(food.timing.file, stringsAsFactors = FALSE)

# read in glucose data
cgm.readings = readDexcomFile(glucose.file)


########################################################
### Data nnotation: Mark min and max peaks for all data
########################################################

min.peak = 120
min.peak.height = 30
cgm.readings = markGlucosePeaks(cgm.readings, min.peak.height, min.peak)


########################################################
### Data exclusion: only keep dates with recorded meal times
########################################################

# keep only max peaks
cgm.readings = cgm.readings[cgm.readings$peak == "max", ]


# keep only dates with recorded meal times
dates.with.meal.times <- unique(food.times$Date)
cgm.readings <- cgm.readings[which(cgm.readings$GlucoseDisplayDate %in% dates.with.meal.times),] 


########################################################
### Data exclusion -- remove travel dates because sensor time is unreliable switching time zones
########################################################


# remove travel from glucose data
cgm.readings = removeTravelDates(cgm.readings, travel.file, TZ.path)

# remove travel from food.times
food.times = food.times[food.times$Date %in% cgm.readings$GlucoseDisplayDate, ] 

```

# Associate diet and CGM
```{r associateDietCGM}

# combine features from food log with food timing
food.times = addDietaryFeatures(food.times, food.logs)

# associate glucose spikes with food features
cgm.meal.features <- associateFoodAndCGM(cgm.readings, food.times)

# print data set
current.table = cgm.meal.features[sample(1:nrow(cgm.meal.features), 10), ]
head(current.table)

```


### Data exclusion
```{r removeMissingData}

# remove peaks without meals
cgm.meal.features = removePeaksWithoutMeals(cgm.meal.features)


# print final number of observations
peaks = length(cgm.meal.features$peak[cgm.meal.features$peak == "max"])
print(paste(peaks, " total glucose spikes" , sep = ""))
```

### distribution of glucose concentrations
```{r concentrations, include = T, collapse = T}

par(mfrow = c(1,2))
plot(cgm.meal.features$GlucoseValue, main = "Glucose concentration during spike", ylab = "glucose concentration (mg/dL)", cex.main = 0.7)
hist(cgm.meal.features$GlucoseValue, main = "Glucose concentration during spike", xlab = "glucose concentration (mg/dL)", cex.main = 0.7)

plot(cgm.meal.features$glucoseChange, main = "Magnitude of Blood Sugar Spikes", ylab = "glucose concentration (mg/dL)", cex.main = 0.7)
hist(cgm.meal.features$glucoseChange, main = "Magnitude of Blood Sugar Spikes", xlab = "glucose concentration (mg/dL)", cex.main = 0.7)

```

# Select features
```{r selectFeatures, collapse = T}
## remove variables that wont be used for prediction
features = c("timeChange","carbohydrates","glycemicIndex", 
                       "AM","fruit","grain","inulin","banana",     
                        "wine","last_meal_TIME" ,"diversity")
predictors <- cgm.meal.features[,names(cgm.meal.features) %in% features]

```

### Final feature matrix
```{r featureMatrix}
head(predictors)
```


# Data transformation
```{r finalTransformations}
# define a data frame with predictors and response
outcome.predictors = cbind(cgm.meal.features$glucoseChange, predictors)

# only time since last meal was transformed
outcome.predictors$last_meal_TIME = log(outcome.predictors$last_meal_TIME)

```


# Relationship between predictors and outcome
```{r predictorOutcomes, collapse = T}
par(mfrow = c(3,3))
## compare the predictors with the outcome to find the relationship
plot(outcome.predictors$carbohydrates, outcome.predictors[, 1], ylab = "glucose change", xlab = "carbohydrates", pch = 20)
plot(outcome.predictors$glycemicIndex, outcome.predictors[, 1], ylab = "glucose change", xlab = "glycemix index", pch = 20)  # glycemic index mostly 0
plot(outcome.predictors$diversity, outcome.predictors[, 1], ylab = "glucose change", xlab = "diversity", pch = 20)
plot(outcome.predictors$fruit, outcome.predictors[, 1], ylab = "glucose change", xlab = "fruit", pch = 20)
plot(outcome.predictors$banana, outcome.predictors[, 1], ylab = "glucose change", xlab = "banana", pch = 20)
plot(outcome.predictors$inulin, outcome.predictors[, 1], ylab = "glucose change", xlab = "inulin", pch = 20)
plot(outcome.predictors$wine, outcome.predictors[, 1], ylab = "glucose change", xlab = "wine", pch = 20)
plot(outcome.predictors$AM, outcome.predictors[, 1], ylab = "glucose change", xlab = "AM", pch = 20)
plot(outcome.predictors$last_meal_TIME, outcome.predictors[, 1], ylab = "glucose change", xlab = "log(time since last meal)", pch = 20)
```



## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
